---
fixtures:
  repositories:
    archive: 'https://github.com/voxpupuli/puppet-archive.git'
    cron: 'https://github.com/voxpupuli/puppet-cron.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    yumrepo_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
      puppet_version: '>= 6.0.0'
